ValorTechnology/Controllers/CotizacionesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using AppService.Interfaces;
using AutoMapper;
using Domain;
using Microsoft.Ajax.Utilities;
using ValorTechnology.ViewModels;

namespace ValorTechnology.Controllers
{
    public class CotizacionesController : Controller
    {
        private IProductoService _productoService;
        private ITipoProductoService _tipoProductoService;
        private ICotizacionService _cotizacionService;
        private IDetalleCotizacionService _detalleCotizacionService;

        public CotizacionesController(IProductoService productoService,
            ITipoProductoService tipoProductoService,
            ICotizacionService cotizacionService,
            IDetalleCotizacionService detalleCotizacionService
            )
        {
            _productoService = productoService;
            _tipoProductoService = tipoProductoService;
            _cotizacionService = cotizacionService;
            _detalleCotizacionService = detalleCotizacionService;
        }
        
        public ActionResult Index()
        {
            ViewBag.Cotizaciones = _cotizacionService.GetAll().Count();

            ViewBag.Productos = _productoService.GetAll().Count();

            var listado = _cotizacionService.GetAll().ToList();

            return View(listado);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Save(CotizacionViewModel cotizacion)
        {
            var newCotizacion = _cotizacionService.Insert(new Cotizacion
            {
                Monto = cotizacion.Monto,
                NombreCliente = cotizacion.NombreCliente,
                NombreVendedor = cotizacion.NombreVendedor,
                Ruc = cotizacion.Ruc,
                Email =  cotizacion.Email
            });

            cotizacion.DetalleCotizacion.ForEach(a =>
                {
                    _detalleCotizacionService.Insert(new DetalleCotizacion
                    {
                        Precio = a.Precio,
                        Descuento = a.Descuento,
                        IdProducto = a.IdProducto,
                        Impuesto = a.Impuesto,
                        Cantidad = a.Cantidad,
                        Subtotal = a.Subtotal,
                        IdCotizacion = newCotizacion.IdCotizacion
                    });
                }
            );

            return RedirectToAction("Index");
        }

        public JsonResult ListadoProductos(string idProductos)
        {
            var ids = new JavaScriptSerializer().Deserialize<IList<int>>(idProductos);

            var list = _productoService.GetAll().ToList();

            var productos = Mapper.Map<List<ProductosViewModel>>(list);

            productos.ForEach(a => { a.DescripcionTipo = _tipoProductoService.GetById(a.TipoProducto_Id).Tipo; });
            
            ids?.ForEach(a =>
            {
                productos = productos.Where(x => x.IdProducto != a).ToList();
            });

            return Json(productos, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Ver(int idCotizacion)
        {
            var cotizacion = _cotizacionService.GetAll().FirstOrDefault(x => x.IdCotizacion == idCotizacion);

            var detalle = _detalleCotizacionService.GetDetalleCotizaciones(idCotizacion);
            
            var cotizacionVm = new CotizacionViewModel
            {
                DetalleCotizacion = Mapper.Map<List<DetalleCotizacionViewModel>>(detalle),
                Email = cotizacion?.Email,
                NombreCliente = cotizacion?.NombreCliente,
                Ruc = cotizacion?.Ruc,
                Monto = cotizacion?.Monto,
                NombreVendedor = cotizacion?.NombreVendedor,
            };

            cotizacionVm.DetalleCotizacion.ForEach(a =>
                {
                    a.Producto = _productoService.GetById(a.IdProducto).Descripcion;
                });

            return View(cotizacionVm);
        }
    }
}

ValorTechnology/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppService.Interfaces;
using AppService.Services;
using Data;
using Domain;

namespace ValorTechnology.Controllers
{
    public class ProductosController : Controller
    {
        ITipoProductoService _tiposProductosService;
        IProductoService _productoService;

        public ProductosController(ITipoProductoService tiposProductosService, IProductoService productoService)
        {
            _tiposProductosService = tiposProductosService;
            _productoService = productoService;
        }

        public ActionResult Index()
        {
            return View(_productoService.GetAll());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var producto = _productoService.GetById(id);

            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        public ActionResult Create()
        {
            ViewBag.TiposProductos = _tiposProductosService.GetAll().Select(x => new SelectListItem { Text = x.Tipo, Value = x.Id.ToString() }).ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Producto producto)
        {
            if (ModelState.IsValid)
            {
                producto.DeletedAt = null;
                _productoService.Insert(producto);
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var producto = _productoService.GetById(id);

            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Producto producto)
        {
            if (ModelState.IsValid)
            {
                _productoService.Update(producto);

                return RedirectToAction("Index");
            }
            return View(producto);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var producto = _productoService.GetById(id);

            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var producto = _productoService.GetById(id);

            _productoService.Delete(producto);

            return RedirectToAction("Index");
        }
    }
}

ValorTechnology/Controllers/TipoProductosController.cs
using System.Net; 
using System.Web.Mvc;
using AppService.Interfaces; 
using Domain;

namespace ValorTechnology.Controllers
{
    public class TiposProductosController : Controller
    {
        ITipoProductoService _tiposProductosService;

        public TiposProductosController(ITipoProductoService tiposProductosService)
        {
            _tiposProductosService = tiposProductosService;
        } 
       
        public ActionResult Index()
        {
            return View(_tiposProductosService.GetAll());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tiposProductos = _tiposProductosService.GetById(id);

            if (tiposProductos == null)
            {
                return HttpNotFound();
            }
            return View(tiposProductos);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TiposProductos tiposProductos)
        {
            if (ModelState.IsValid)
            {
                tiposProductos.DeletedAt = null;
                _tiposProductosService.Insert(tiposProductos); 
                return RedirectToAction("Index");
            }

            return View("Create");
        }
         
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tiposProductos = _tiposProductosService.GetById(id);

            if (tiposProductos == null)
            {
                return HttpNotFound();
            }

            return View(tiposProductos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TiposProductos tiposProductos)
        {
            if (ModelState.IsValid)
            {
                _tiposProductosService.Update(tiposProductos);

                return RedirectToAction("Index");
            }
            return View(tiposProductos);
        }
         
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tiposProductos = _tiposProductosService.GetById(id);

            if (tiposProductos == null)
            {
                return HttpNotFound();
            }

            return View(tiposProductos);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var tiposProductos = _tiposProductosService.GetById(id);

            _tiposProductosService.Delete(tiposProductos);

            return RedirectToAction("Index");
        }
    }
}

ValorTechnology/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Valor Technology</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/css/skins/skin-blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Cotizaciones")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>V</b>T</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Valor</b>Technology</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            @Html.Partial("~/Views/Shared/_Sidebar.cshtml")
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) --> 

            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->

                @RenderBody()


            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>  
        </footer>

        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>

    <!-- jQuery 3 -->
    <script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Content/bower_components/moment/min/moment.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/js/demo.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

ValorTechnology/Views/Shared/_Sidebar.cshtml
<section class="sidebar">

    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu</li>
        <li class="active treeview">
            <a href="#">
                <i class="fa fa-dashboard"></i> <span>Cotizaciones</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="active"><a href="@Url.Action("Index", "Cotizaciones")"><i class="fa fa-circle-o"></i> Listado</a></li>
                <li><a href="@Url.Action("Create", "Cotizaciones")"><i class="fa fa-circle-o"></i> Crear nueva</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-folder"></i> <span>Productos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("Index", "Productos")"><i class="fa fa-circle-o"></i> Listado</a></li>
                <li><a href="@Url.Action("Create", "Productos")"><i class="fa fa-circle-o"></i> Crear nueva</a></li>
            </ul>
        </li>
        
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Tipo Productos</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("Index", "TiposProductos")"><i class="fa fa-circle-o"></i> Listado</a></li>
                <li><a href="@Url.Action("Create", "TiposProductos")"><i class="fa fa-circle-o"></i> Crear nuevo</a></li>
            </ul>
        </li>
    </ul>
</section>